import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toast } from "@/components/ui/toast";
import { ToastProvider } from "@radix-ui/react-toast";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider afterSignOutUrl="/auth/sign-in">
      <html lang="en" >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem 
            disableTransitionOnChange>
          <header>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>

              </SignedIn>
          </header>
          <ToastProvider>
            <main>{children}
              <Toast/>
            </main>
            </ToastProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
